model_param:
  mode: LLM
  run_type: training
  tied_embeddings: false
  model_type: glm4_moe
  global_batch_size: 160
  gradient_accumulation_steps: 1
  seq_len: 16356
  decode_len: 1024
  hidden_dim: 4096
  attention:
    attention_type: gqa
    num_heads: 96
    kv_heads: 8
    head_dim: 128
    use_flashattention: true # Enable FlashAttention optimization (when false, we model naive attention without causal masking or flash optimizations)
    attention_tile_size: 128
  intermediate_size: 10944
  moe:
    num_experts: 128
    top_k: 8
    moe_intermediate_size: 1408
    n_shared_experts: 1
    moe_layer_freq: 1
    first_k_dense_replace: 1
  vocab_size: 151552
  num_layers: 46
