model_param:
  mode: "LLM"
  run_type: "inference"
  model_type: "llama"  # gpt assumes dense-style architecture with GELU; llama assumes llama-style architecture with SwiGLU
  batch_size: 1
  seq_len: 2048
  decode_len: 1024
  hidden_dim: 8192
  attention:
    attention_type: "gqa"  # one of "mha","gqa","mla"
    num_heads: 64
    kv_heads: 8
  ffn_dim: 28672
  ffn_mult: null
  vocab_size: 128256
  num_layers: 80
  n_tokens: null
  all_reduce: "every layer"
inference_param:
  sample_every: -1
