model_param:
  mode: "LLM"  # Mode of operation
  run_type: "inference" # Type of run: "training" or "inference"
  tied_embeddings: true  # Share input and output embedding weights (WIP: affects memory estimation only)
  model_type: "llama"  # gpt assumes dense-style architecture with GELU; llama assumes llama-style architecture with SwiGLU
  batch_size: 1  # Sequences per global batch
  seq_len: 2048  # Total context length (prefill + decode_len for inference)
  decode_len: 1024 # Number of tokens to decode during inference
  hidden_dim: 4096 # Transformer hidden dimension
  attention: # Attention-related parameters
    attention_type: "gqa"  # Supported attention types: "mha" or "gqa" ("mla" not implemented)
    num_heads: 32 # Total number of attention heads
    kv_heads: 8  # Number of key/value heads (used only when attention_type = "gqa")
    use_flashattention: true  # Enable FlashAttention optimization
    attention_tile_size: 128  # Tile size used in attention computation
  num_experts: 1   # Number of experts in MoE layers. Set to 1 to disable MoE.
  top_k: 1   # Number of active experts per token in MoE
  intermediate_size: 14336 # Output dimension of the first FFN layer (typically 4Ã—hidden_dim)
  vocab_size: 128256  # Vocabulary size
  num_layers: 32 # Number of transformer layers
