model_param:
  mode: "LLM"
  run_type: "inference"
  tied_embeddings: true
  model_type: "llama"  # gpt assumes dense-style architecture with GELU; llama assumes llama-style architecture with SwiGLU
  batch_size: 1
  seq_len: 2048
  decode_len: 1024
  hidden_dim: 4096
  attention:
    attention_type: "gqa"  # one of "mha","gqa","mla"
    num_heads: 32
    kv_heads: 8
  ffn_dim: 14336
  ffn_mult: null
  vocab_size: 128256
  num_layers: 32
inference_param:
  sample_every: -1
